# Generated by Django 5.2.7 on 2025-11-11 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('check', 'Cheque'), ('transfer', 'Transferencia Electrónica')], default='check', max_length=10, verbose_name='Medio de Pago')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entidad Financiera')),
                ('account_type', models.CharField(blank=True, choices=[('savings', 'Ahorros'), ('checking', 'Corriente')], max_length=10, null=True, verbose_name='Tipo de Cuenta')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='NonPolicyHolderInsuredDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insured_name', models.CharField(blank=True, default='-', max_length=100, verbose_name='Nombres y Apellidos del Asegurado')),
                ('insured_id_number', models.CharField(blank=True, default='-', max_length=20, verbose_name='C.C. del Asegurado')),
                ('relationship_to_claimant', models.CharField(blank=True, default='-', max_length=50, verbose_name='Parentesco con el Reclamante')),
                ('policy_numbers', models.TextField(blank=True, default='N/A', verbose_name='Número(s) de Pólizas')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50, unique=True)),
                ('policy_type', models.CharField(choices=[('life', 'Seguro de Vida'), ('health', 'Salud y Hospitalización'), ('accident', 'Accidentes Personales')], default='life', max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diligenciamiento_city', models.CharField(blank=True, default='-', max_length=50, verbose_name='Ciudad de Diligenciamiento')),
                ('diligenciamiento_date', models.DateField(verbose_name='Fecha de Diligenciamiento')),
                ('claimant_cc', models.CharField(blank=True, default='-', max_length=20, verbose_name='C.C.')),
                ('claimant_address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Dirección de Correspondencia')),
                ('claimant_phone', models.CharField(blank=True, default='-', max_length=20, verbose_name='Teléfono')),
                ('claimant_email', models.EmailField(blank=True, default='ejemplo@metlife.com', max_length=254, verbose_name='Email')),
                ('claimant_celular', models.CharField(blank=True, default='-', max_length=20, verbose_name='Celular')),
                ('acts_on_behalf', models.BooleanField(default=True, verbose_name='Actúa en nombre de todos los beneficiarios')),
                ('claimant_is_insured', models.BooleanField(default=True, verbose_name='El reclamante es el asegurado')),
                ('incident_location', models.CharField(blank=True, default='-', max_length=255, verbose_name='Lugar del Siniestro')),
                ('incident_date', models.DateField(verbose_name='Fecha del Siniestro')),
                ('incident_time', models.TimeField(verbose_name='Hora del Siniestro')),
                ('incident_cause', models.TextField(blank=True, default='-', verbose_name='Causa del Siniestro')),
                ('incident_description', models.TextField(blank=True, default='-', verbose_name='Descripción del Siniestro')),
                ('occupation_at_incident', models.CharField(blank=True, default='-', max_length=100, verbose_name='Ocupación a la fecha del Siniestro')),
                ('last_work_date', models.DateField(blank=True, null=True, verbose_name='Último día de trabajo')),
                ('has_recent_hospitalization', models.BooleanField(default=False, verbose_name='Estuvo hospitalizado/tratamiento en los últimos años')),
                ('disability_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Estructuración (Incapacidad T.P.)')),
                ('is_drunk_accident', models.BooleanField(blank=True, null=True, verbose_name='Estaba en estado de embriaguez (Accidente)')),
                ('accident_injuries', models.TextField(blank=True, verbose_name='Descripción de las lesiones (Accidente)')),
                ('accident_details', models.TextField(blank=True, verbose_name='Detalle del Accidente')),
                ('medical_reimbursement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Reembolso')),
                ('hospitalization_days', models.IntegerField(blank=True, null=True, verbose_name='Días de Hospitalización (Renta Diaria)')),
                ('hospital_entry_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso (Renta Diaria)')),
                ('hospital_exit_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida (Renta Diaria)')),
                ('temp_disability_start', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio (Incapacidad Temporal)')),
                ('temp_disability_end', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización (Incapacidad Temporal)')),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('claimant_signature', models.CharField(blank=True, default='-', max_length=150, verbose_name='Firma del Reclamante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('Approved', 'Aprobado'), ('Rejected', 'Rechazado'), ('Draft', 'Borrador')], default='Draft', max_length=20)),
                ('insured_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.nonpolicyholderinsureddetails')),
                ('payment_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.claimpaymentdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimOtherInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, default='N/A', max_length=100)),
                ('company', models.CharField(blank=True, default='N/A', max_length=100)),
                ('insured_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_insurances', to='client.usersolicitation')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(blank=True, default='N/A', max_length=150, verbose_name='Enfermedad')),
                ('attention_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Atención')),
                ('doctor_name', models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Nombre del Médico')),
                ('doctor_contact', models.CharField(blank=True, default='N/A', max_length=150, verbose_name='Dirección y Teléfono')),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='client.usersolicitation')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.CharField(choices=[('Muerte Natural', 'Muerte Natural'), ('Enfermedad Graves', 'Enfermedad Graves'), ('Renta Diaria por Hospitalización', 'Renta Diaria por Hospitalización'), ('Muerte Accidental', 'Muerte Accidental'), ('Desmembración', 'Desmembración'), ('Gastos Médicos', 'Gastos Médicos'), ('Incapacidad Total y Permanente', 'Incapacidad Total y Permanente'), ('Fracturas', 'Fracturas'), ('Quemaduras', 'Quemaduras')], max_length=50)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='client.usersolicitation')),
            ],
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_users', to='client.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'policy')},
            },
        ),
    ]
