# Generated by Django 5.2.7 on 2025-11-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimmedicalhistory',
            name='solicitation',
        ),
        migrations.RemoveField(
            model_name='claimotherinsurance',
            name='solicitation',
        ),
        migrations.RemoveField(
            model_name='usersolicitation',
            name='insured_details',
        ),
        migrations.RemoveField(
            model_name='usersolicitation',
            name='acts_on_behalf',
        ),
        migrations.RemoveField(
            model_name='usersolicitation',
            name='claimant_is_insured',
        ),
        migrations.AddField(
            model_name='usersolicitation',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='client.policy'),
        ),
        migrations.DeleteModel(
            name='ClaimCoverage',
        ),
        migrations.DeleteModel(
            name='ClaimMedicalHistory',
        ),
        migrations.DeleteModel(
            name='ClaimOtherInsurance',
        ),
        migrations.DeleteModel(
            name='NonPolicyHolderInsuredDetails',
        ),
    ]
