# Generated by Django 5.2.7 on 2025-11-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_claimmedicalhistory_solicitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersolicitation',
            name='diligenciamiento_date',
        ),
        migrations.AddField(
            model_name='usersolicitation',
            name='document_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace a Documentos (Drive, etc.)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle Insurance'), ('property', 'Property Insurance')], default='vehicle', max_length=20),
        ),
    ]
